language: node_js
node_js:
  - "10"
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn
install:
  - yarn
cache:
  yarn: true
before_script:
  - cd prisma && docker-compose up -d
  - docker ps
  - sleep 20
  - ../node_modules/.bin/prisma deploy
  - cd ..
  - yarn build
script:
  - yarn test
