language: node_js
node_js:
  - "10"
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn
  - export DEBUG="*"
  - export DEV_PRISMA_ENDPOINT="http://0.0.0.0:4466"
install:
  - yarn
cache:
  yarn: true
before_script:
  - cd prisma && docker-compose up -d
  - docker ps -a
  - sleep 5
  - docker ps -a
  - ../node_modules/.bin/prisma deploy
  - ../node_modules/.bin/prisma generate
  - cd ..
  - yarn build
script:
  - yarn test
