language: nodejs
sudo: required
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs
cache:
  yarn: true
before_script:
  - yarn
  - yarn build
script:
  - yarn test
