language: node_js
node_js:
  - "10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn
install:
  - yarn
cache:
  yarn: true
before_script:
  - yarn build
script:
  - yarn test
