language: nodejs
sudo: required
before_install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - apt-get install -y nodejs
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
before_script:
  - yarn
  - yarn build
script:
  - yarn test
